name: On tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    uses: ./.github/workflows/publish-release.yml
    with:
      ref: ${{ github.ref }}
    permissions:
      contents: write
  publish-npm:
    uses: ./.github/workflows/publish-npm.yml
    with:
      ref: ${{ github.ref }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: read
      id-token: write
