name: Publish release

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ workflow.inputs.ref }}
      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
