name: Publish Package to npmjs (manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to publish
        required: true
jobs:
  publish-npm:
    uses: ./.github/workflows/publish-npm.yml
    with:
      ref: refs/tags/${{ inputs.tag }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
