name: Publish release (manual)
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to publish
        required: true
jobs:
  publish-release:
    uses: ./.github/workflows/publish-release.yml
    with:
      ref: refs/tags/${{ inputs.tag }}
